if("$ENV{ROOTFS}" STREQUAL "")
    message(FATAL_ERROR "Define the ROOTFS environment variable to point to the appropriate sysroot.")
else()
    set(SYSROOT_PATH "$ENV{ROOTFS}")
endif()

message(STATUS "Using sysroot: ${SYSROOT_PATH}")

set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_SYSROOT "${SYSROOT_PATH}")
set(CMAKE_FIND_ROOT_PATH "${SYSROOT_PATH}")
set(CMAKE_SYSTEM_NAME "Linux")

if(NOT "$ENV{CC}" STREQUAL "")
   set(CMAKE_C_COMPILER "$ENV{CC}")
else()
   set(CMAKE_C_COMPILER clang)
endif()

if(NOT "$ENV{CXX}" STREQUAL "")
    set(CMAKE_CXX_COMPILER "$ENV{CXX}")
else()
    set(CMAKE_CXX_COMPILER clang++)
endif()

set(CMAKE_C_COMPILER_TARGET ${CMAKE_LIBRARY_ARCHITECTURE})
set(CMAKE_CXX_COMPILER_TARGET ${CMAKE_LIBRARY_ARCHITECTURE})

set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld")
set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
