name: Build Apple

on:
  push:
    branches:
      - master
      - dev
      - "release/*"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build"
        working-directory: ${{github.workspace}}
        run: scripts/build_apple.sh
