name: Build and Test iOS

on:
  push:
    branches:
      - master
      - dev
      - "release/*"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build and Test"
        run: |
          DEVICE=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed 's/Simulator//g' | awk '{$1=$1;print}'`
          echo "Selected testing device : ${DEVICE}"
          xcodebuild build-for-testing -project CBL_C.xcodeproj -scheme "CouchbaseLiteTests-iOS-App" -destination "platform=iOS Simulator,name=${DEVICE}" | xcpretty
          xcodebuild test-without-building -project CBL_C.xcodeproj -scheme "CouchbaseLiteTests-iOS-App" -destination "platform=iOS Simulator,name=${DEVICE}"
