name: Build Android

on:
  push:
    branches:
      - master
      - dev
      - 'release/*'
  pull_request:
    branches:
      - '**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # NOTE: If we decide to archive the build products we should build with RelWithDebInfo instead.
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Android SDK
      run: |
        $ANDROID_SDK_ROOT/tools/bin/sdkmanager --install "ndk;21.4.7075529"
        $ANDROID_SDK_ROOT/tools/bin/sdkmanager --install "cmake;3.18.1"
    - name: Build
      working-directory: ${{github.workspace}}
      run: scripts/build_android.sh
    
